name: Build Kk Pages Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Build Docker image
        run: |
          docker image build --file docker/nuxt/Dockerfile -t kk-pages --build-arg API_ENV=prod --build-arg PROJECT_NAME=kk-pages ./
          docker login -u ${ALIYUN_DOCKER_USERNAME} -p ${ALIYUN_DOCKER_PASSWORD} registry.cn-beijing.aliyuncs.com
          docker tag kk-pages registry.cn-beijing.aliyuncs.com/xk-repo/kk-pages:latest
          docker push registry.cn-beijing.aliyuncs.com/xk-repo/kk-pages:latest
        env:
          ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}