name: Deploy Vercel

on:
  workflow_dispatch:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.5.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm install netlify-cli -g

      - name: Deploy to Netlify
        run: |
          cp apps/kk-pages/env/.env.prod apps/kk-pages/.env.local
          pnpm --F @kk-project/kk-pages run build
        env:
          SERVER_PRESET: netlify_builder

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --filter @kk-project/kk-pages ${{ steps.extract_branch.outputs.branch == 'master' && '--prod' || '' }}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_API_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 0
